<?php

class StaticData{

    public static function states($select2 = false){

        $states = array(
            'AL' => 'Alabama',
            'AK' => 'Alaska',
            'AS' => 'American Samoa',
            'AZ' => 'Arizona',
            'AR' => 'Arkansas',
            'CA' => 'California',
            'CO' => 'Colorado',
            'CT' => 'Connecticut',
            'DE' => 'Delaware',
            'DC' => 'District Of Columbia',
            'FM' => 'Federated States Of Micronesia',
            'FL' => 'Florida',
            'GA' => 'Georgia',
            'GU' => 'Guam',
            'HI' => 'Hawaii',
            'ID' => 'Idaho',
            'IL' => 'Illinois',
            'IN' => 'Indiana',
            'IA' => 'Iowa',
            'KS' => 'Kansas',
            'KY' => 'Kentucky',
            'LA' => 'Louisiana',
            'ME' => 'Maine',
            'MH' => 'Marshall Islands',
            'MD' => 'Maryland',
            'MA' => 'Massachusetts',
            'MI' => 'Michigan',
            'MN' => 'Minnesota',
            'MS' => 'Mississippi',
            'MO' => 'Missouri',
            'MT' => 'Montana',
            'NE' => 'Nebraska',
            'NV' => 'Nevada',
            'NH' => 'New Hampshire',
            'NJ' => 'New Jersey',
            'NM' => 'New Mexico',
            'NY' => 'New York',
            'NC' => 'North Carolina',
            'ND' => 'North Dakota',
            'MP' => 'Northern Mariana Islands',
            'OH' => 'Ohio',
            'OK' => 'Oklahoma',
            'OR' => 'Oregon',
            'PW' => 'Palau',
            'PA' => 'Pennsylvania',
            'PR' => 'Puerto Rico',
            'RI' => 'Rhode Island',
            'SC' => 'South Carolina',
            'SD' => 'South Dakota',
            'TN' => 'Tennessee',
            'TX' => 'Texas',
            'UT' => 'Utah',
            'VT' => 'Vermont',
            'VI' => 'Virgin Islands',
            'VA' => 'Virginia',
            'WA' => 'Washington',
            'WV' => 'West Virginia',
            'WI' => 'Wisconsin',
            'WY' => 'Wyomin',
        );

        if($select2){
            $stateLists = array();
            foreach ($states as $id => $name) {
                $stateLists[] = array(
                    'id'    => $id,
                    'text'  => $name
                );
            }

            return $stateLists;
        }else{
            return $states;
        }
    }

    public static function dogBreeds($select2 = false){
        $dogBreeds = array(
            'Affenpinscher',
            'Afghan Hound',
            'Airedale Terrier',
            'Akbash',
            'Akita',
            'Alaskan Malamute',
            'American Bulldog',
            'American Eskimo Dog',
            'American Hairless Terrier',
            'American Staffodshire Terrier',
            'American Water Spaniel',
            'Anatolian Shepherd',
            'Appenzell Mountain Dog',
            'Australian Cattle Dog/Blue Heeler',
            'Austrailan Kelpie',
            'Australian Shepherd',
            'Australian Terrier',
            'Besenji',
            'Basset Hound',
            'Beagle',
            'Bearded Collie',
            'Beauceron',
            'Bedlington Terrier',
            'Belgian Shepherd Dog Sheepdog',
            'Belgian Shepherd Lakenois',
            'Belgian Shepherd Malinois',
            'Belgian Shepherd Tervuren',
            'Bernese Mountain Dog',
            'Bichon Frise',
            'Black and Tan Coonhound',
            'Black Labrador Retriever',
            'Black Mouth Cur',
            'Black Russian Terrier',
            'Bloodhound',
            'Blue Lacy',
            'Bluestick Coonhound',
            'Boerboel',
            'Bolognese',
            'Border Collie',
            'Border Terrier',
            'Borzoi',
            'Boston Terrier',
            'Bouvier des Flanders',
            'Boxer',
            'Boykin Spaniel',
            'Briard',
            'Brittany Spaniel',
            'Brussels Griffon',
            'Bull Terrier',
            'Bullmastiff',
            'Cairn Terrier',
            'Canaan Dog',
            'Cane Corso Mastiff',
            'Carolina Dog',
            'Catahoula Leopard Dog',
            'Cattle Dog',
            'Caucasian Shepherd (Caucasian Ovcharka)',
            'Cavalier King Charles Spaniel',
            'Chesapeake Bay Retriever',
            'Chihuahua',
            'Chinese Crested Dog',
            'Chinese Foo Dog',
            'Chinook',
            'Chocolate Labrador Retriever',
            'Chow Chow',
            'Cimenco dell\'Etna',
            'Clumber Spaniel',
            'Cockapoo',
            'Cocker Spaniel',
            'Collie',
            'Coonhound',
            'Corgi',
            'Coton de Tulear',
            'Curly-Coated Retriever',
            'Dachshund',
            'Dalamatian',
            'Dandi Dinmont Terrier',
            'Doberman Pinscher',
            'Dogo Argentio',
            'Dogue de Bordeaux',
            'Dutch Shepherd',
            'English Bulldog',
            'English Cocker Spaniel',
            'English Coonhound',
            'English Pointer',
            'English Setter',
            'English Shepherd',
            'English Springer Spaniel',
            'English Toy Spaniel',
            'Entlebucher',
            'Eskimo Dog',
            'Feist',
            'Field Spaniel',
            'Fila Brasileiro',
            'Finnish Lapphund',
            'Finnish Spitz',
            'Flat-Coated Retriever',
            'Fox Terrier',
            'Foxhound',
            'French Bulldog',
            'Galgo Spanish Greyhound',
            'German Pinscher',
            'German Shepherd Dog',
            'German Shorthaired Pointer',
            'German Spitz',
            'German Wirehaired Pointer',
            'Giant Schnauzer',
            'Glen of Imaal Terrier',
            'Golden Terrier',
            'Gordon Setter',
            'Great Dane',
            'Great Pyrenees',
            'Great Swiss Mountain Dog',
            'Harrier',
            'Havanese',
            'Hound ',
            'Hovawart',
            'Husky',
            'Ibizan Hound',
            'Illyrian Sheepdog',
            'Irish Setter',
            'Irish Terrier',
            'Irish Water Spaniel',
            'Irish Wolfhound',
            'Italian Greyhound',
            'Italian Spinone',
            'Jack Russell Terrier',
            'Japanese Chin',
            'Jindo',
            'Kai Dog',
            'Karelian Bear Dog',
            'Keeshond',
            'Kerry Blue Terrier',
            'Kishnu',
            'Klee Kai',
            'Komondor',
            'Kuvasz',
            'Kyi Leo',
            'Labrador Retriever',
            'Lakeland Terrier',
            'Lancashire Heeler',
            'Leonberger',
            'Lhasa Apso',
            'Lowchen',
            'Maltese',
            'Manchester Terrier',
            'Maremma Sheepdog',
            'Mastiff',
            'McNab',
            'Miniature Pinscher',
            'Mixed Breed Dog',
            'Mountain Cur',
            'Montain Dog',
            'Munsterlander',
            'Neopolitan Dog',
            'New Guinea Singing Dog',
            'Norfolk Terrier',
            'Norwegian Buhund',
            'Norwegian Elkhound',
            'Norwegian Lundhund',
            'Norwich Terrier',
            'Nova Scotia Duck - Trolling Retriever',
            'Old English Sheepdog',
            'Otterhound',
            'Papillon',
            'Patterdale Terrier (Fell Terrier)',
            'Pekingese',
            'Peruvian Inca Orchid',
            'Petit Basset Griffon Vendeen',
            'Pharaoh Hound',
            'Pit Bull Terrier',
            'Plott hound',
            'Pondengo Portugueso',
            'Pointer',
            'Polish Lowland Sheepdog',
            'Pomeranian',
            'Poodle',
            'Portuguese Water Dog',
            'Presa Canario',
            'Pug',
            'Puli',
            'Pumi',
            'Rat Terrier',
            'Redbone Coonhound',
            'Retriever',
            'Rhodesian Ridgeback',
            'Rottweiler',
            'Saint Bernard ',
            'Saluki',
            'Samoyed',
            'Sarplaninac',
            'Schipperke',
            'Schnauzer',
            'Scottish Deerhound',
            'Scottish Terrier Scottie',
            'Sealyham Terrier',
            'Setter',
            'Shar Pei',
            'Sheep Dog',
            'Shepherd',
            'Shetland Sheepdog Sheltie',
            'Shiba Inu',
            'Shih Tzu',
            'Siberian Husky',
            'Silky Terrier',
            'Skye Terrier',
            'Sloughi',
            'Smooth Fox Terrier',
            'South Russian Ovtcharka',
            'Spaniel',
            'Spitz',
            'Staffordshire Bull Terrier',
            'Standard Poodle',
            'Sussex Spaniel',
            'Swedish Vallhund',
            'Terrier',
            'Thai Ridgeback',
            'Tibetian Mastiff',
            'Tibetian Spaniel',
            'Tibetian Terrier',
            'Tosa Inu',
            'Troy Fox Terrier',
            'Treeing Walker Coonhound',
            'Vizsla',
            'Weimaraner',
            'Welsh Corgi',
            'Welsh  Springer Spaniel',
            'Welsh Terrier',
            'West Highland White Terrier Westie',
            'Wheaten Terrier',
            'Whippet',
            'White German Shepherd',
            'Wire Fox Terrier',
            'Wire-Haired Pointing Griffon',
            'Wirehaired Terrier',
            'Xoloitzcuintle/Mexican Hairless',
            'Yellow Labrador  Retriever',
            'Yorkshire Terrier Yorkie',
        );

        if(!$select2){
            return $dogBreeds;
        }else{
            $breeds = array();
            foreach ($dogBreeds as $breed) {
                $breeds[] = array(
                    'id'    => $breed,
                    'text'  => $breed
                );
            }

            return $breeds;
        }
    }

    public static function catBreeds($select2 = false){
        $catBreeds = array(
            'Domestic Longhair',
            'Domestic Shorthair',
            'Abyssinian',
            'American Bobtail',
            'American Curl',
            'American Shorthair',
            'American Wirehair',
            'Balinese',
            'Bengal',
            'Birman',
            'Bombay',
            'British Shorthair',
            'Burmese',
            'Chartreux',
            'Cornish Rex',
            'Cymric',
            'Devon Rex',
            'Egyptian Mau',
            'Exotic Shorthair',
            'Havana Brown',
            'Himalayan',
            'Japanese Bobtail',
            'Javanese',
            'Korat',
            'Maine Coon',
            'Manx',
            'Munchkin',
            'Nebelung',
            'Norwegian Forest Cat',
            'Ocicat',
            'Oriental',
            'Persian',
            'Ragdoll',
            'Russian Blue',
            'Scottish Fold',
            'Selkirk Rex',
            'Siamese',
            'Siberian',
            'Singapura',
            'Snowshoe',
            'Somali',
            'Sphynx',
            'Tonkinese',
            'Turkish Angora',
            'Turkish Van'
        );

        if(!$select2){
            return $catBreeds;
        }else{
            $breeds = array();
            foreach ($catBreeds as $breed) {
                $breeds[] = array(
                    'id'    => $breed,
                    'text'  => $breed
                );
            }

            return $breeds;
        }
    }
}